language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - postgis
  postgresql: "9.5"
services:
  - postgresql
before_script:
  - psql -U postgres -c "create extension postgis"
  - psql -c 'create database veganaut-test;' -U postgres
