language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - postgresql-9.5-postgis-2.3
  postgresql: "9.5"
services:
  - postgresql
before_script:
  - psql -U postgres -c 'create database "veganaut-test";'
  - psql -U postgres -d veganaut-test -c 'create extension postgis'
  - psql -U postgres -d veganaut-test -f ./migrations/2018-09-setup-postgres-tables.sql
